# Generated by Django 3.0.8 on 2020-09-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_divar_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divar',
            name='author',
        ),
    ]
