# Generated by Django 3.1.1 on 2020-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200929_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divar',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
